name: Build Docker Production Image

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: [self-hosted, GameServer]
    steps:
      - name: Run build-server script
        run: ~/build-server
